services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:${Z2M_VERSION}
    profiles: [z2m]
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8099:8080
    devices:
      # Make sure this matched your adapter location
      - ${Z2MPATH}:/dev/ttyACM0

  homeassistant:
    container_name: homeassistant
    image: nakata5321/riscv-homeassistant:${HA_VERSION}
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/homeassistant:/srv/homeassistant/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
